Repository grails/grails-data-hibernate5, pull requests merged in 2021-12, with the labels that each got.

#417 Fixed Groovydoc by extending documentation from compileClasspath
  build.gradle
Labels: type: bug

#418 Add new section build to the release notes workflow
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: type: ci

#419 Use gradle-build-action for Java CI workflow
  .github/workflows/gradle.yml
Labels: type: ci

#420 Gradle Improvements
  gradle.properties
  grails-datastore-gorm-hibernate5/build.gradle
  settings.gradle
Labels: type: build

#428 Update Hibernate5 Javadoc link in the Asiidocs
  docs/src/docs/asciidoc/advancedGORMFeatures/eventsAutoTimestamping.adoc
  docs/src/docs/asciidoc/advancedGORMFeatures/ormdsl/customHibernateTypes.adoc
  docs/src/docs/asciidoc/advancedGORMFeatures/ormdsl/tableAndColumnNames.adoc
  docs/src/docs/asciidoc/configuration/hibernateCustomization.adoc
  docs/src/docs/asciidoc/persistenceBasics/locking.adoc
  docs/src/docs/asciidoc/querying/criteria.adoc
Labels: type: docs

#438 Update dependency grails-testing-support to 2.3.1
  gradle.properties
Labels: type: dependency upgrade

#443 Delete .travis.yml
  .travis.yml
Labels: type: ci

#444 Delete travis-build.sh
  travis-build.sh
Labels: type: ci

#445 Delete travis-publish.sh
  travis-publish.sh
Labels: type: ci

#446 Delete secring.gpg.enc
  secring.gpg.enc
Labels: type: ci

#448 Update dependency asset-pipeline to 3.3.4
  gradle.properties
Labels: type: dependency upgrade

#236 Fix composite ID not visible to JPA
  grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java
  grails-datastore-gorm-hibernate5/src/test/groovy/grails/gorm/tests/compositeid/CompositeIdCriteria.groovy
  grails-datastore-gorm-hibernate5/src/test/groovy/grails/gorm/tests/compositeid/CompositeIdWithDeepOneToManyMappingSpec.groovy
  grails-datastore-gorm-hibernate5/src/test/groovy/org/grails/orm/hibernate/compiler/HibernateEntityTransformationSpec.groovy
Labels: type: bug

#451 Fix problem with tenantId part of Composite identifier
  examples/grails-data-service/grails-app/conf/application.yml
  examples/grails-data-service/grails-app/domain/example/MultitenantBook.groovy
  grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java
Labels: type: bug
