Repository grails/grails-data-hibernate5, pull requests merged in 2025-02, with the labels that each got.

#985 fix grails/gorm-hibernate5#973 for grails-7 (9.0.x)
  grails-database-migration/src/main/groovy/org/grails/plugins/databasemigration/command/ApplicationContextDatabaseMigrationCommand.groovy
Labels: bug

#986 Exclude liquibase-commercial from being exported
  grails-database-migration/build.gradle
Labels: maintenance, ci

#981 Handle loading migrations from embedded jars (plugins)
  grails-database-migration/src/main/groovy/org/grails/plugins/databasemigration/liquibase/EmbeddedJarPathHandler.groovy
  grails-database-migration/src/main/resources/META-INF/services/liquibase.resource.PathHandler
Labels: migration-plugin
